site_name: SCGB notes
site_description: A cool description
site_url: https://alexnegron.github.io/scgb-note

theme:
    name: 'material'
    #custom_dir: overrides
    language: en
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
# Extensions
markdown_extensions:
  - footnotes
  - mdx_math
  
  #- attr_list
  #- sane_lists
  #- meta
  #- smarty
  #- tables
  #- mdx_breakless_lists
  
  - pymdownx.arithmatex:
      generic: true
  
  #- pymdownx.magiclink
  #- pymdownx.critic
  #- pymdownx.caret
  #- pymdownx.keys
  #- pymdownx.mark
  #- pymdownx.tilde
  #- pymdownx.highlight:
  #    use_pygments: true
  #    anchor_linenums: true
  #- pymdownx.tasklist:
  #     custom_checkbox: true
  #- pymdownx.emoji:
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - nl2br
  - pymdownx.details
  - toc:
      permalink: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences:
#       custom_fences:
#         - name: dataview
#           class: dataview
#           format: !!python/name:pymdownx.superfences.fence_div_format
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:mermaid2.fence_mermaid
  
extra_javascript:
  - assets/js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search
  #- ezlinks:
  #      wikilinks: true
  #- mermaid2
  #- awesome-pages
  #- tooltipster-links
  - embed_file
  - roamlinks
