site_name: SCGB notes
site_description: A cool description
site_url: https://alexnegron.github.io/scgb-note

theme:
    name: 'material'
    #custom_dir: overrides
    language: en
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
# Extensions
markdown_extensions:
    - footnotes
    - mdx_math
  # - attr_list
    - pymdownx.arithmatex:
       generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#   - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - admonition
    - nl2br
    - pymdownx.details
    - toc:
        permalink: true
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search
  - embed_file
  - roamlinks
